# -*- coding: utf-8 -*-
"""Homework1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10UWHjw3ZKkv1wfCft0WqUhSb-BXsuV9M
"""

X = input("Hello , What is your name : ")
print("Hi",X , end=" ")
Y = int(input(", how many sticks do you want : "))
print("Ok, there are",20-Y,"sticks left in pile.")