# -*- coding: utf-8 -*-
"""Quiz 1-5(Day 1).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10BUNmebomz9SzNX2ZknHRObYCIAb4m1n

ANSWER QUIZ 0
"""

print("Hello World,my name is Pichayet Vanichsombut")

"""ANSWER QUIZ 1"""

print(1+3*4,(1+3)*4)

print(1+3*4)
print((1+3)*4)

"""ANSWER QUIZ 2

% จะเเสดงเสษของการหาร
"""

print(84/10,84%10)



"""ANSWER QUIZ 3"""

print(10/2)
print(10.0/2)

print(10.001/2)

"""ANSWER QUIZ 4"""

a = 2
b = 3
X = 5
print("Y =",a*X+b)

"""ANSWER QUIZ 5"""

Name = input("What your name : ")
Age = int(input("How old are you : "))
Year = int(input("This Year : "))
print(Name,"will retire in ",60-Age+Year)

