# -*- coding: utf-8 -*-
"""Quiz2-3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pJk8DiL8yofqhEhkqVrkpStkFebNrHk1

Quiz 2
"""

a = int(input("First number :"))
b = int(input("Second number :"))
if(a<b):
  c = a
else:
  c = b
x = 1
for i in range(1,c+1):
  if((a%i==0)and(b%i==0)):
    x = i
print("The greatest common divisor is",x)

"""Quiz 3"""

a = input("Enter a string :")
x = ""
for i in a:
    x += chr(ord(i)+1)
print("The plus one cypher is",x)

"a" + "b"