# -*- coding: utf-8 -*-
"""Quiz 5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EJHnGcZqaNJgJXVSXhnv0Dl9GzWatWbY
"""

L = list(range(2))
i = 0
n = int(input("what is number do you want? :"))
while i < n-2 :

    L2 = L[0+i]+L[1+i]
    L.append(L2)
    i = i + 1
        

print(L)