# -*- coding: utf-8 -*-
"""Quiz 4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fWiRMuV6HaJSzIOGg-byNBs1kN-dhhgP
"""

x = input("What logic do you want to check? : ")

def F(A,B):
  return(eval(x))

print("The Truth Table")
print("------------------------------------------------------------------")
print("|        A        |        B       |       ",x , " ")
print("------------------------------------------------------------------")
for A in [True,False]:
  for B in [True,False]:
    print("|      " + str(A) + "       |      " + str(B) + "      |    " + str(F(A,B)) + "    " )
    print("------------------------------------------------------------------")